### ISSUE TITLE
RFE: port to `sdl2`

### ISSUE THREAD

**Issue by kloczek** [Libvisual/libvisual#306] opened 2023-04-10 22:59 UTC
Looks like libvisual still uses `sld`.
It would be good to port to `sdl2` pkgconfig API.

Any plans to do that? 🤔

**Comment by hartwork** [comment] 2023-04-10 23:08
Hi @kloczek I've been trying to contact you via e-mail at kloczek@fedoraproject.org twice before this year, on 2023-01-26 and 2023-02-03 precisely. Have my mails been getting through to you? 

Regarding SDL 2 I can say that @kaixiong and I both want a migration to happen, in general.

**Comment by hartwork** [comment] 2023-04-11 00:00
PS: I see now that we have #193 for that, already.

**Comment by hartwork** [comment] 2023-05-24 20:37
Closing as a duplicate of #193…

**Closed by hartwork** 2023-05-24 20:37 UTC
Labels: enhancement
